# fly.toml app configuration file generated for greenhouse-adtecinnovations on 2026-01-19T11:33:57-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'greenhouse-adtecinnovations'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 8080

  # SIM800L: permitir HTTP
  force_https = false

  # No sleep
  auto_stop_machines = "off"
  auto_start_machines = false
  min_machines_running = 1

[[vm]]
  memory = '512mb'
  cpus = 1
  memory_mb = 512
